name: gobuild test

on:
  push:
    branches: [ main ]

jobs:
  first-job:
    name: gobuild
    runs-on: ubuntu-22.04
      container:
        image: golang:1.19.4
        steps:
          - name: build
            env:
              GOPRIVATE: "github.com/predybalov/mysecret"
            run: |
              go get github.com/predybalov/mysecret
