name: gobuild testing

on:
  push:
    branches: [ master ]

jobs:
  first-job:
    name: gobuild
    runs-on: ubuntu-22.04
    container:
      image: golang:1.19.4
      env:
        GOPRIVATE: "github.com/predybalov/mysecret"
        GO111MODULE: "on"
        GIT_TERMINAL_PROMPT: 1
        TOKEN: ${{ secrets.TOKEN }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v3.1.0
        
      - name: build
        run: |
          git config --global url."https://${TOKEN}@github.com/".insteadOf "https://github.com/"
          go install github.com/predybalov/mysecret
          go run gotest.go
          
