name: gobuild testing

on:
  push:
    branches: [ master ]

jobs:
  first-job:
    name: gobuild
    runs-on: ubuntu-22.04
    container:
      image: golang:1.19.4
      env:
        GOPRIVATE: "github.com/predybalov/mysecret"
        GO111MODULE: on
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        
      - name: build            
        run: |
          echo $GITHUB_CONTEXT
          pwd
          ls -la
          ls -la /go
          go env
          git config --global url."https://${{ secrets.GITHUB_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
          go install github.com/predybalov/mysecret@latest


