name: gobuild testing

on:
  push:
    branches: [ master ]

jobs:
  first-job:
    name: gobuild
    runs-on: ubuntu-22.04
    container:
      image: golang:1.19.4
      env:
        GOPRIVATE: "github.com/predybalov/mysecret"
        GO111MODULE: on
    steps:
      - name: Git checkout
        uses: actions/checkout@v3.1.0
        
      - name: build            
        run: |
          pwd
          ls -la
          ls -la /go
          go env
          git config --global url."https://$GITHUB_ACTOR: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@github.com/".insteadOf "https://github.com/"
          go install github.com/predybalov/mysecret@latest
